apiVersion: v1
data:
  server.conf: |
    # Use HTTP 1.1 to allow for keepalive connections
    proxy_http_version 1.1;

    # Pass the request host header through to the upstream
    proxy_set_header Host $host;

    # Allow http connections to be kept open
    proxy_set_header Connection '';

    # Pass the origin server response header through rather than allowing nginx to set it to "nginx"
    proxy_pass_header Server;

    location /api {
        proxy_set_header Sitespect-Enabled "1";
        proxy_set_header X-Forwarded-For $http_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto "http";
        proxy_set_header Host "www.section.io";
        proxy_pass http://api-service:8080;
    }

    location / {
        proxy_set_header Sitespect-Enabled "1";
        proxy_set_header X-Forwarded-For $http_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto "http";
        proxy_set_header Host "www.section.io";
        proxy_pass http://storefront-service:8080;
    }
kind: ConfigMap
metadata:
  name: router-config
